using System;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using FluentAssertions;
using UglyToad.PdfPig.Core;
using UglyToad.PdfPig.Fonts.Standard14Fonts;
using UglyToad.PdfPig.Writer;
using Xunit;
using static Luminous.InSign.Tests.InSignTriangulation.FlatContractGeometry;

namespace Luminous.InSign.Tests.InSignTriangulation;

/// <summary>
/// Regenerates flat-contract.pdf (next to this file), the test document for the inSign icebreaker
/// test.
/// The output is a deliberately "flat" PDF: it contains no AcroForm dictionary, no annotations,
/// and no inSign ##SIG text tags. Signature boxes must therefore be placed purely via API
/// coordinates, which is exactly the scenario Luminous targets. Two dashed rectangles are painted
/// where <see cref="CoordinateBasedSigningSessionTests" /> places the signature fields so a human
/// signer can visually verify that the API coordinates line up.
/// The generated bytes are deterministic, so the file only changes in git when the layout changes.
/// </summary>
public sealed class FlatContractPdfGenerator
{
    private const double LeftMargin = 57.0;
    private const double LineWidth = 0.75;
    private const double DashLength = 3.0;

    private static readonly string[] BodyText =
    [
        "1. SUBJECT OF THE AGREEMENT",
        "",
        "The Licensor grants the Licensee a non-exclusive, non-transferable right",
        "to use the software product \"Luminous Test Suite\" for internal business",
        "purposes. The license covers installation on up to five workstations at",
        "a single site of the Licensee.",
        "",
        "2. TERM AND TERMINATION",
        "",
        "This agreement enters into force upon signature by both parties and runs",
        "for an initial term of twelve months. It renews automatically for further",
        "periods of twelve months unless terminated in writing with three months",
        "notice before the end of the respective term.",
        "",
        "3. REMUNERATION",
        "",
        "The annual license fee amounts to EUR 4,800.00 plus statutory VAT and is",
        "due within 30 days after invoicing. Late payments accrue interest at the",
        "statutory rate applicable to commercial transactions.",
        "",
        "4. GOVERNING LAW",
        "",
        "This agreement is governed by the laws of the Federal Republic of Germany.",
        "The exclusive place of jurisdiction is Munich."
    ];

    private readonly ITestOutputHelper _output;

    public FlatContractPdfGenerator(ITestOutputHelper output) => _output = output;

    [Fact(Explicit = true)]
    public void GenerateFlatContractPdf()
    {
        var pdfBytes = RenderFlatContract();
        RenderFlatContract()
           .SequenceEqual(pdfBytes)
           .Should()
           .BeTrue("the generator must be deterministic so the checked-in PDF does not churn in git");

        var pdfText = Encoding.Latin1.GetString(pdfBytes);
        pdfText.Should().NotContain("/AcroForm", "the test document must not contain interactive form fields");
        pdfText.Should().NotContain("/Annots", "the test document must not contain annotations");
        pdfText.Should().NotContain("##SIG", "the test document must not contain inSign text tags");

        var targetPath = Path.Combine(Path.GetDirectoryName(GetSourceFilePath())!, "flat-contract.pdf");
        File.WriteAllBytes(targetPath, pdfBytes);
        _output.WriteLine($"wrote {targetPath} ({pdfBytes.Length} bytes)");
    }

    private static byte[] RenderFlatContract()
    {
        // PdfPig uses PDF-native coordinates: points with the origin at the bottom-left page
        // corner, matching FlatContractGeometry. Text positions are baseline start points.
        using var builder = new PdfDocumentBuilder();
        var helvetica = builder.AddStandard14Font(Standard14Font.Helvetica);
        var helveticaBold = builder.AddStandard14Font(Standard14Font.HelveticaBold);
        var page = builder.AddPage(PageWidth, PageHeight);

        // Title.
        InsertLine(85.0, "SOFTWARE LICENSE AGREEMENT", helveticaBold, 18);
        InsertLine(
            105.0,
            "between the Licensor and the Licensee (test document, not a real contract)",
            helvetica,
            10
        );

        // Body paragraphs.
        var y = 145.0;
        foreach (var line in BodyText)
        {
            if (line.Length > 0)
            {
                var isHeading = char.IsDigit(line[0]);
                InsertLine(y, line, isHeading ? helveticaBold : helvetica, isHeading ? 11 : 10);
            }

            y += 14.5;
        }

        // Signature section heading.
        InsertLine(PageHeight - BoxBottomY - BoxHeight - 40.0, "5. SIGNATURES", helveticaBold, 11);

        // Dashed placeholder rectangles plus role labels underneath.
        DrawSignaturePlaceholder(page, helvetica, LicensorBoxX, "Licensor");
        DrawSignaturePlaceholder(page, helvetica, LicenseeBoxX, "Licensee");

        return PinTrailerId(builder.Build());

        void InsertLine(double yFromTop, string text, PdfDocumentBuilder.AddedFont font, double fontSize) =>
            page.AddText(text, fontSize, new PdfPoint(LeftMargin, PageHeight - yFromTop), font);
    }

    private static void DrawSignaturePlaceholder(
        PdfPageBuilder page,
        PdfDocumentBuilder.AddedFont labelFont,
        double boxX,
        string label
    )
    {
        page.SetStrokeColor(153, 153, 153);
        DrawDashedLine(page, new PdfPoint(boxX, BoxBottomY), new PdfPoint(boxX + BoxWidth, BoxBottomY));
        DrawDashedLine(
            page,
            new PdfPoint(boxX, BoxBottomY + BoxHeight),
            new PdfPoint(boxX + BoxWidth, BoxBottomY + BoxHeight)
        );
        DrawDashedLine(page, new PdfPoint(boxX, BoxBottomY), new PdfPoint(boxX, BoxBottomY + BoxHeight));
        DrawDashedLine(
            page,
            new PdfPoint(boxX + BoxWidth, BoxBottomY),
            new PdfPoint(boxX + BoxWidth, BoxBottomY + BoxHeight)
        );
        page.ResetColor();
        page.AddText(label, 10, new PdfPoint(boxX, BoxBottomY - 16.0), labelFont);
    }

    // PdfPig does not expose the line dash pattern operator, so the dashed border is painted as
    // individual short line segments (3 points on, 3 points off).
    private static void DrawDashedLine(PdfPageBuilder page, PdfPoint from, PdfPoint to)
    {
        var totalLength = Math.Sqrt(Math.Pow(to.X - from.X, 2) + Math.Pow(to.Y - from.Y, 2));
        var unitX = (to.X - from.X) / totalLength;
        var unitY = (to.Y - from.Y) / totalLength;
        for (var offset = 0.0; offset < totalLength; offset += 2 * DashLength)
        {
            var end = Math.Min(offset + DashLength, totalLength);
            page.DrawLine(
                new PdfPoint(from.X + offset * unitX, from.Y + offset * unitY),
                new PdfPoint(from.X + end * unitX, from.Y + end * unitY),
                LineWidth
            );
        }
    }

    // PdfPig randomizes the trailer /ID (two 32-digit hex strings) on every build and offers no
    // API to control it. Replacing the hex digits with a constant of the same length is
    // binary-safe because the trailer is located behind every byte offset the file refers to.
    private static byte[] PinTrailerId(byte[] pdfBytes)
    {
        var pdfText = Encoding.Latin1.GetString(pdfBytes);
        pdfText = Regex.Replace(
            pdfText,
            @"/ID \[ <[0-9A-Fa-f]{32}><[0-9A-Fa-f]{32}>\]",
            "/ID [ <4C756D696E6F7573466C6174436F6E74><4C756D696E6F7573466C6174436F6E74>]"
        );
        return Encoding.Latin1.GetBytes(pdfText);
    }

    private static string GetSourceFilePath([CallerFilePath] string sourceFilePath = "") => sourceFilePath;
}
